version: '3'
services:
    mysql:
        image: "mysql:5.7"
        environment:
            MYSQL_ALLOW_EMPTY_PASSWORD: "TRUE"
        volumes:
            - ./mysqlinit:/docker-entrypoint-initdb.d
    redis:
        image: "redis:alpine"
    stemweb_py27:
        build: .
        ports:
            - "10.0.228.35:8000:8000"        ### on test-server
            - "10.0.228.35:51000:51000"      ### on test server
            #- "127.0.0.1:8000:8000"         ### on dev-laptop
            #- "127.0.0.1:51000:51000"       ### on dev-laptop
            #- "127.0.0.1:3000:3000"         ### on dev-laptop
